# A Helm Chart for deploying an IOC instance
apiVersion: v2
name: domain

version: 1.0.0

type: application

dependencies:
  - name: ioc-instance
    version: "1.4.1"
    # repository: "oci://ghcr.io/epics-containers"
    repository: "file:///scratch/hgv27681/work/ec-helm-charts/Charts/ioc-instance"
